POST https://api.ai.qq.com/fcgi-bin/ocr/ocr_generalocr
content-type:  application/x-www-form-urlencoded

app_id=1106550426
&image=iVBORw0KGgoAAAANSUhEUgAAAGQAAAAyCAYAAACqNX6+AAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAACCSURBVHhe7dExAQAADMOg+Tfd2eAIFriFUgimEEwhmEIwhWAKwRSCKQRTCKYQTCGYQjCFYArBFIIpBFMIphBMIZhCMIVgCsEUgikEUwimEEwhmEIwhWAKwRSCKQRTCKYQTCGYQjCFYArBFIIpBFMIphBMIZhCMIVgCsEUgikEUwhle6Uw1mTKw5c5AAAAAElFTkSuQmCC
&nonce_str=1550686933
&sign=FAB300DB1CA1952FF17ABA99D1DFD563
&time_stamp=1550688073